[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test/foundry'
cache_path  = 'forge-cache'
solc = "0.8.18" # to use a specific local solc install set the path as `solc = "<path to solc>/solc"`
extra_output_files = ['metadata']

optimizer = true
optimizer_runs = 10000

[rpc_endpoints]
mainnet = "${ALCHEMY_API}"
goerli = "${ALCHEMY_GOERLI_API}"

# See more config options https://github.com/foundry-rs/foundry/tree/master/config